services:
  - type: web
    name: my-assistant
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: ADMIN_ID
        value: "8473507682"
      - key: OMDAA_API_KEY
        sync: false
      - key: OMDAA_SESSION_ID
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"
